# Generated by Django 5.2 on 2025-07-17 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True)),
                ("glassdoor_rating", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AP", "Applied"),
                            ("HR", "HR Interview"),
                            ("TT", "Technical Test"),
                            ("IN", "Interviewing"),
                            ("OF", "Offer Received"),
                            ("RJ", "Rejected"),
                            ("AC", "Accepted"),
                        ],
                        default="AP",
                        max_length=2,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LN", "LinkedIn"),
                            ("IN", "Indeed"),
                            ("GH", "GitHub"),
                            ("WS", "Company Website"),
                            ("RF", "Referral"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("applied_date", models.DateField()),
                ("notes", models.TextField(blank=True, default="")),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                ("referral_contact", models.CharField(blank=True, max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_type", models.CharField(max_length=100)),
                ("interviewer", models.CharField(blank=True, max_length=100)),
                ("date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("follow_up", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.jobapplication",
                    ),
                ),
            ],
        ),
    ]
