# Generated by Django 5.2 on 2025-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
