# Generated by Django 5.2 on 2025-07-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="interview",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-applied_date"]},
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="applications", to="applications.tag"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="is_remote",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("AP", "Applied"),
                    ("HR", "HR Interview"),
                    ("TT", "Technical Test"),
                    ("IN", "Interviewing"),
                    ("OF", "Offer Received"),
                    ("RJ", "Rejected"),
                    ("AC", "Accepted"),
                ],
                db_index=True,
                default="AP",
                max_length=2,
            ),
        ),
    ]
